#include <QObject>
#include <QString>
#include <QMap>
namespace analogic
{
namespace ws
{
struct ScannerFaultInfo
{
    QString description;
    QString useraction;
};
class ScannerFaultData : public QObject
{
 Q_OBJECT
public:
ScannerFaultData(){}
QMap <QString, ScannerFaultInfo>     m_scannerfaultinfo;
void insertScannerFaultData()
{
m_scannerfaultinfo.insert("MSG_NOT_RECEIVED",{tr("Scanner: General fault, message not received."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MSG_NOT_SENT",{tr("Scanner: General fault, message not sent."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MSG_REPLY_ERROR",{tr("Scanner: General fault, no reply to message."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MSG_REPLY_UNKNOWN",{tr("Scanner: General fault, unknown message reply."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DEADLINE_REACHED",{tr("Scanner: General fault, deadline reached."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("EVENT_PUBLISH_FAULT",{tr("Scanner: General fault, event publishing."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("PERSIST_DATA_FAULT",{tr("Scanner: General fault, data persist."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RETRIEVE_DATA_FAULT",{tr("Scanner: General fault, data retrival."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("CANNOT_REVERSE_CONVEYOR_IN_SCAN_MODE",{tr("Scanner: General fault, cannot reverse conveyor direction while in scan."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_CONTROL_MOTION_KEYSWITCH_INTERLOCK_VIOLATION",{tr("Scanner: X-ray / motion control keyswitch disabled."),tr("1) Enable the X-Ray / Motion control keyswitch at key panel. \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ACCESS_PANEL_INTERLOCK_VIOLATION",{tr("Scanner: General fault, access panel interlock."),tr("1) Contact a service technician.")});
m_scannerfaultinfo.insert("GANTRY_NOT_AT_SPEED_NOR_AT_HOME_INTERLOCK_VIOLATION",{tr("Scanner: General fault, gantry not at speed nor at home position."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("CANNOT_MAXIMIXE_XRAYS_NOT_ON",{tr("Scanner: General fault, cannot maximize X-rays, X-rays are not on."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("COMMAND_FAILURE",{tr("Scanner: General fault, command failed."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("CONTROL_SEQUENCE_ERROR",{tr("Scanner: General fault, control sequence error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("CONTROL_SEQUENCE_TIMEOUT",{tr("Scanner: General fault, control sequence timeout."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("PROCESS_EXITED",{tr("Scanner: General fault, control process exited."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ENTRANCE_ESTOP_PRESSED",{tr("Scanner: Entrance emergency stop activated."),tr("1) Reset Entrance Emergency Stop button when safe. \n2) Press the blue interlock reset button at key pannel. \n3) Select scan when ready to continue screening. \n4) If issue persists, contact a service technician.")});
m_scannerfaultinfo.insert("EXIT_ESTOP_PRESSED",{tr("Scanner: Exit emergency stop activated."),tr("1) Reset Exit Emergency Stop button when safe. \n2) Press the blue interlock reset button at key pannel. \n3) Select scan when ready to continue screening. \n4) If issue persists, contact a service technician.")});
m_scannerfaultinfo.insert("CONSOLE_ESTOP_PRESSED",{tr("Scanner: Console emergency stop activated."),tr("1) Reset Console Emergency Stop button when safe. \n2) Press the blue interlock reset button at key pannel. \n3) Select scan when ready to continue screening. \n4) If issue persists, contact a service technician.")});
m_scannerfaultinfo.insert("REMOTE_ESTOP_PRESSED",{tr("Scanner: Conveyor system emergency stop activated."),tr("1) Reset Remote Emergency Stop button when safe. \n2) Press the blue interlock reset button at key pannel. \n3) Select scan when ready to continue screening. \n4) If issue persists, contact a service technician.")});
m_scannerfaultinfo.insert("SYSTEM_COMM_ERROR",{tr("Scanner: General fault, system communication error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SOFTWARE_INTRUSION_DETECTED",{tr("Scanner: General fault, software intrusion detected."),tr("1) A software reinstall is required to recover. \n2) Contact a service technician for assistance.")});
m_scannerfaultinfo.insert("ANONYMOUS_IO_FAULT",{tr("Scanner: General fault, I/O."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RCB_FAULT",{tr("Scanner: General fault, RCB."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_ARC_FAULT",{tr("Scanner: General fault, X-ray arc or over temperature fault."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_ANODE_OVER_KV_FAULT",{tr("Scanner: General fault, X-ray anode over voltage."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_CATHODE_OVER_KV_FAULT",{tr("Scanner: General fault, X-ray cathode over voltage."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("INTERLOCK_OPEN_FAULT",{tr("Scanner: General fault, X-ray interlock open."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OVER_CURRENT_FAULT",{tr("Scanner: General fault, X-ray over current."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OVER_VOLTAGE_FAULT",{tr("Scanner: General fault, X-ray over voltage."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OVERTEMP_FAULT",{tr("Scanner: General fault, X-ray over temperature or arc fault."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWER_LIMIT_FAULT",{tr("Scanner: General fault, X-ray power limit."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("REGULATION_FAULT",{tr("Scanner: General fault, X-ray regulation."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DISK_SPEED_FAULT",{tr("Scanner: General fault, gantry over speed."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_VOLTAGE_FAULT",{tr("Scanner: General fault, X-ray voltage."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_CURRENT_FAULT",{tr("Scanner: General fault, X-ray current."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWERLINK_COMMAND_FAULT",{tr("Scanner: General fault, power link."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_CMD_BITS_MISMATCH_FAULT",{tr("Scanner: General fault, X-ray uplink control bit error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SAFETY_IO_FAULT",{tr("Scanner: General fault, safety controller sensor."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_DRIVE_FAULT",{tr("Scanner: General fault, motor drive."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("STATUS_FAULT",{tr("Scanner: General fault, status error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWERLINK_DISABLED",{tr("Scanner: General fault, powerlink status is disabled."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_FAULT_CLEAR_TIMEOUT",{tr("Scanner: General fault, cannot clear X-ray fault."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ACCESS_PANELS_LOCKING_FAULT",{tr("Scanner: Right or left center access panel locking fault."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("LEFT_ACCESS_PANEL_INTERLOCK_FAULT",{tr("Scanner: Left access panel interlock is not engaged."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("LEFT_ACCESS_PANEL_SOLENOID_STATUS_FAULT",{tr("Scanner: Left access panel locking fault."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("LEFT_ACCESS_PANEL_SOLENOID_LOCKED_STATUS_FAULT",{tr("Scanner: Left access panel locking fault."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RIGHT_ACCESS_PANEL_INTERLOCK_FAULT",{tr("Scanner: Right access panel interlock is not engaged."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RIGHT_ACCESS_PANEL_SOLENOID_STATUS_FAULT",{tr("Scanner: Right access panel locking fault."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RIGHT_ACCESS_PANEL_SOLENOID_LOCKED_STATUS_FAULT",{tr("Scanner: Right access panel locking fault."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTION_CONTACTORS_STATUS_FAULT",{tr("Scanner: General fault, motor controller contactor."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWERLINK_CONTACTORS_STATUS_FAULT",{tr("Scanner: General fault, powerlink contactor."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROTATIONAL_ENVELOPE_VIOLATION_SENSOR_FAULT",{tr("Scanner: General fault, gantry area sensor."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("STANDSTILL_MONITOR_FAULT",{tr("Scanner: General fault, gantry stopped sensor."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OVERSPEED_FAULT",{tr("Scanner: General fault, over speed sensor."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ENVELOPE_SENSOR",{tr("Scanner: General fault, gantry area sensor."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("STANDSTILL_MONITOR",{tr("Scanner: General fault, gantry stopped sensor."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SPEED_FAULT",{tr("Scanner: General fault, over speed sensor."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("UNKNOWN",{tr("Scanner: General fault - unknown."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("FILE_READ_ERROR",{tr("Scanner: General fault, file read error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("GENERAL_INIT_ERROR",{tr("Scanner: General fault, initialization error."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("GPU_LIB_INIT_ERROR",{tr("Scanner: General fault, GPU library initialization."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OFFSET_CAL_FAULT",{tr("Scanner: General fault, offset calibration."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("AIR_CAL_FAULT",{tr("Scanner: General fault, air calibration."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("NOT_READY_FOR_CMD_FAULT",{tr("Scanner: General fault, not ready."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("BUFFER_POOL_FAULT",{tr("Scanner: General fault, memory buffer pool."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("VIEW_SUBSCRIBE_TIMEOUT",{tr("Scanner: General fault, view subscribe timeout."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RECON_VIEW_BLOCK_FAULT",{tr("Scanner: General fault, reconstruction view block."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("TOO_MANY_BAD_VIEWS",{tr("Scanner: General fault, too many bad views."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DYNAMIC_CAL_FAULT",{tr("Scanner: General fault, dynamic calibration failed."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DEFAULT_CAL_FILE_FAULT",{tr("Scanner: General fault, default calibration file not found."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OVER_MAX_BAG_QUEUE",{tr("Scanner: General fault, maximum bag queue size reached."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("INVALID_BAG_DATA",{tr("Scanner: General fault, invalid bag data."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("HIGH_TEMPERATURE_WARNING",{tr("Scanner: General fault, system temperature is too high."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("HIGH_TEMPERATURE_FAULT",{tr("Scanner: General fault, system temperature is too high."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("OUT_OF_BAGS",{tr("Scanner: General fault, system has run out of bag memory."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("LOW_ON_BAGS",{tr("Scanner: General fault, system has is low on bag memory."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MODBUS_PLC_CONNECTION_ERROR",{tr("ACS: General fault, scanner to PLC communications."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MODBUS_ENTRANCE_RFID_CONNECTION_ERROR",{tr("ACS: General fault, entrance RFID communications lost."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MODBUS_EXIT_RFID_CONNECTION_ERROR",{tr("ACS: General fault, exit RFID communications lost."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ENTRANCE_BAG_JAM_ERROR",{tr("Scanner: Bag jam detected at the entrance of the scanner."),tr("1) Clear the bag jam from the entrance tunnel of the scanner. \n2) Press Scan button to resume scanning items. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("EXIT_BAG_JAM_ERROR",{tr("Scanner: Bag jam detected at the exit of the scanner."),tr("1) Clear the bag jam from the exit tunnel of the scanner. \n2) Press Scan button to resume scanning items. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("TUNNEL_BAG_JAM_ERROR",{tr("Scanner: Bag jam detected inside the scanner tunnel."),tr("1) Clear the bag jam from the tunnel of the scanner. \n2) Press Scan button to resume scanning items. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("GENERAL_BHS_ERROR",{tr("Scanner: General fault, conveyor system."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("BHS_NOT_RTR",{tr("Scanner: General fault, conveyor system not ready to receive bags."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE2",{tr("ACS: General fault, zone 2 motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE2",{tr("ACS: General fault, zone 2 sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE2",{tr("ACS: General fault, zone 2 motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE2",{tr("ACS: General fault, zone 2 sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE2",{tr("ACS: General fault, zone 2 motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE2",{tr("ACS: General fault, zone 2 motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE3",{tr("ACS: General fault, zone 3 motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE3",{tr("ACS: General fault, zone 3 sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE3",{tr("ACS: General fault, zone 3 motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE3",{tr("ACS: General fault, zone 3 sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE3",{tr("ACS: General fault, zone 3 motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE3",{tr("ACS: General fault, zone 3 motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE3B",{tr("ACS: General fault, zone 3B motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE3B",{tr("ACS: General fault, zone 3B sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE3B",{tr("ACS: General fault, zone 3B motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE3B",{tr("ACS: General fault, zone 3B sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE3B",{tr("ACS: General fault, zone 3B motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE3B",{tr("ACS: General fault, zone 3B motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE4",{tr("ACS: General fault, zone 4 motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE4",{tr("ACS: General fault, zone 4 sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE4",{tr("ACS: General fault, zone 4 motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE4",{tr("ACS: General fault, zone 4 sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE4",{tr("ACS: General fault, zone 4 motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE4",{tr("ACS: General fault, zone 4 motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE7",{tr("ACS: General fault, zone 7 motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE7",{tr("ACS: General fault, zone 7 sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE7",{tr("ACS: General fault, zone 7 motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE7",{tr("ACS: General fault, zone 7 sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE7",{tr("ACS: General fault, zone 7 motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE7",{tr("ACS: General fault, zone 7 motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_SLAVE_MISSING_ZONE8",{tr("ACS: General fault, zone 8 motor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_SLAVE_MISSING_ZONE8",{tr("ACS: General fault, zone 8 sensor missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_POWER_FAILURE_ZONE8",{tr("ACS: General fault, zone 8 motor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SENSOR_POWER_FAILURE_ZONE8",{tr("ACS: General fault, zone 8 sensor power failure."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_UNDER_VOLTAGE_ZONE8",{tr("ACS: General fault, zone 8 motor under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MOTOR_OVER_CURRENT_ZONE8",{tr("ACS: General fault, zone 8 motor over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_SLAVE_MISSING_ZONE5",{tr("ACS: General fault, zone 5 diverter slave missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_SLAVE_MISSING_ZONE5",{tr("ACS: General fault, zone 5 roller slave missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_AT_FAULT_ZONE5",{tr("ACS: General fault, zone 5 roller."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_AT_FAULT_ZONE5",{tr("ACS: General fault, zone 5 diverter."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_UNDER_VOLTAGE_ZONE5",{tr("ACS: General fault, zone 5 roller under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_OVER_CURRENT_ZONE5",{tr("ACS: General fault, zone 5 roller over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_UNDER_VOLTAGE_ZONE5",{tr("ACS: General fault, zone 5 diverter under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_OVER_CURRENT_ZONE5",{tr("ACS: General fault, zone 5 diverter over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_SLAVE_MISSING_ZONE6",{tr("ACS: General fault, zone 5 diverter slave missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_SLAVE_MISSING_ZONE6",{tr("ACS: General fault, zone 6 roller slave missing."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_AT_FAULT_ZONE6",{tr("ACS: General fault, zone 6 roller."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_AT_FAULT_ZONE6",{tr("ACS: General fault, zone 6 diverter."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_UNDER_VOLTAGE_ZONE6",{tr("ACS: General fault, zone 6 roller under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ROLLER_OVER_CURRENT_ZONE6",{tr("ACS: General fault, zone 6 roller over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_UNDER_VOLTAGE_ZONE6",{tr("ACS: General fault, zone 6 diverter under voltage."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_OVER_CURRENT_ZONE6",{tr("ACS: General fault, zone 6 diverter over current."),tr("1) Powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SYSTEM_COMM_ERROR",{tr("Scanner: General fault, system communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("NETWORK_OFFLINE",{tr("Scanner: General fault, network offline."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("BHS_OFFLINE",{tr("Scanner: General fault, conveyor system offline."),tr("1) Power on or powercycle the Automated Conveyance System (ACS). \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SCC_OFFLINE",{tr("Scanner: General fault, scanner control computer offline."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("UPS_OFFLINE",{tr("Scanner: General fault, UPS offline."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DRB_OFFLINE",{tr("Scanner: General fault, DRB communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("SAFETY_IO_OFFLINE",{tr("Scanner: General fault, Safety I/O controller communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("RCB_OFFLINE",{tr("Scanner: General fault, RCB communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("XRAY_OFFLINE",{tr("Scanner: General fault, X-ray controller communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("GANTRY_OFFLINE",{tr("Scanner: General fault, RCB communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("TEMP_HUMIDITY_SENSOR_OFFLINE",{tr("Scanner: General fault, temperature / humidity sensor offline."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWERLINK_OFFLINE",{tr("Scanner: General fault, powerlink communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DCB_1_OFFLINE",{tr("Scanner: General fault, DCB1 communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DCB_2_OFFLINE",{tr("Scanner: General fault, DCB 2 communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DCB_3_OFFLINE",{tr("Scanner: General fault, DCB 3 communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DCB_4_OFFLINE",{tr("Scanner: General fault, DCB 4 communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DCB_5_OFFLINE",{tr("Scanner: General fault, DCB 5 communications."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("POWER_METER_OFFLINE",{tr("Scanner: General fault, power meter offline."),tr("1) Press Scan button to resume scanning items. \n2) If issue is not resolved, power cycle the Scanner. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("UPS_BAD_COMM",{tr("Scanner: General fault, UPS communications."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("UPS_NO_COMM",{tr("Scanner: General fault, no UPS communications."),tr("1) Power cycle the Scanner. \n2) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("UPS_REPLACE_BATTERY",{tr("Scanner: General fault, replace UPS battery."),tr("1) Call service technician to replace UPS battery.")});
m_scannerfaultinfo.insert("COMPUTER_DRIVE_FULL",{tr("Scanner: General fault, hard drive is full."),tr("1) Call service technician to fix the hard drive.")});
m_scannerfaultinfo.insert("COMPUTER_RAID_NOT_MOUNTED",{tr("Scanner: General fault, RAID drive is not operational."),tr("1) Call service technician to fix the RAID drive.")});
m_scannerfaultinfo.insert("COMPUTER_NETWORK_LOW_SPEED",{tr("Scanner: General fault, network connection is degraded."),tr("1) Call service technician to fix the RAID drive.")});
m_scannerfaultinfo.insert("XRAY_MOTOR_POWER_KEY_SWITCH_DISABLED",{tr("Scanner: General fault, X-Ray key switch is OFF."),tr("1) Turn X-Ray key switch to the ON position. \n2) Resume previous activity. \n3) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("MANUAL_RESET_NEEDED",{tr("Scanner: Manual reset needed (flashing blue button)."),tr("1) Press the blue button and then to clear the fault press the Scan or Stop button.")});
m_scannerfaultinfo.insert("ASI_MODULE_ERROR",{tr("ACS: ASi Module Error."),tr("1) Hold BHS Reset button until light flashes. \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("DIVERTER_DIRECTION_CONFIG_ERROR",{tr("ACS: Diverter Direction Configuration Error."),tr("1) Hold BHS Reset button until light flashes. \n2) Press Scan button to resume scanning items. \n3) If issue is not resolved, power cycle the Scanner. \n4) If issue persists contact a service technician.")});
m_scannerfaultinfo.insert("ASI_TERMINAL_MISSING",{tr("ACS: ASi Master Terminal EL6201 missing."),tr("1) Contact a service technician.")});
}
QMap<QString, ScannerFaultInfo> getScannerFaultData()
{
return m_scannerfaultinfo;
}
};
}
}
