// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/MessageReply.proto

#ifndef PROTOBUF_proto_2fMessageReply_2eproto__INCLUDED
#define PROTOBUF_proto_2fMessageReply_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace analogic {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fMessageReply_2eproto();
void protobuf_AssignDesc_proto_2fMessageReply_2eproto();
void protobuf_ShutdownFile_proto_2fMessageReply_2eproto();

class MsgReply;

enum MSG_REPLY_ID {
  TIMEOUT = 0,
  SENT = 1,
  RECEIVED = 2,
  REJECTED = 3,
  MSG_REPLY_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MSG_REPLY_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MSG_REPLY_ID_IsValid(int value);
const MSG_REPLY_ID MSG_REPLY_ID_MIN = TIMEOUT;
const MSG_REPLY_ID MSG_REPLY_ID_MAX = REJECTED;
const int MSG_REPLY_ID_ARRAYSIZE = MSG_REPLY_ID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_REPLY_ID_descriptor();
inline const ::std::string& MSG_REPLY_ID_Name(MSG_REPLY_ID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_REPLY_ID_descriptor(), value);
}
inline bool MSG_REPLY_ID_Parse(
    const ::std::string& name, MSG_REPLY_ID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG_REPLY_ID>(
    MSG_REPLY_ID_descriptor(), name, value);
}
// ===================================================================

class MsgReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:analogic.MsgReply) */ {
 public:
  MsgReply();
  virtual ~MsgReply();

  MsgReply(const MsgReply& from);

  inline MsgReply& operator=(const MsgReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgReply& default_instance();

  void Swap(MsgReply* other);

  // implements Message ----------------------------------------------

  inline MsgReply* New() const { return New(NULL); }

  MsgReply* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgReply& from);
  void MergeFrom(const MsgReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .analogic.MSG_REPLY_ID msg_reply_id = 1;
  void clear_msg_reply_id();
  static const int kMsgReplyIdFieldNumber = 1;
  ::analogic::MSG_REPLY_ID msg_reply_id() const;
  void set_msg_reply_id(::analogic::MSG_REPLY_ID value);

  // @@protoc_insertion_point(class_scope:analogic.MsgReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int msg_reply_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fMessageReply_2eproto();
  friend void protobuf_AssignDesc_proto_2fMessageReply_2eproto();
  friend void protobuf_ShutdownFile_proto_2fMessageReply_2eproto();

  void InitAsDefaultInstance();
  static MsgReply* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgReply

// optional .analogic.MSG_REPLY_ID msg_reply_id = 1;
inline void MsgReply::clear_msg_reply_id() {
  msg_reply_id_ = 0;
}
inline ::analogic::MSG_REPLY_ID MsgReply::msg_reply_id() const {
  // @@protoc_insertion_point(field_get:analogic.MsgReply.msg_reply_id)
  return static_cast< ::analogic::MSG_REPLY_ID >(msg_reply_id_);
}
inline void MsgReply::set_msg_reply_id(::analogic::MSG_REPLY_ID value) {
  
  msg_reply_id_ = value;
  // @@protoc_insertion_point(field_set:analogic.MsgReply.msg_reply_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace analogic

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::analogic::MSG_REPLY_ID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::MSG_REPLY_ID>() {
  return ::analogic::MSG_REPLY_ID_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fMessageReply_2eproto__INCLUDED
