// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Recon.proto

#ifndef PROTOBUF_proto_2fRecon_2eproto__INCLUDED
#define PROTOBUF_proto_2fRecon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace analogic {
namespace ancp00 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fRecon_2eproto();
void protobuf_AssignDesc_proto_2fRecon_2eproto();
void protobuf_ShutdownFile_proto_2fRecon_2eproto();

class ReconCmdMsg;
class ReconEnum;
class ReconStatusMsg;

enum ReconCmdMsg_ReconCommand {
  ReconCmdMsg_ReconCommand_OFFSET_AND_AIR_CAL = 0,
  ReconCmdMsg_ReconCommand_OFFSET_CAL = 1,
  ReconCmdMsg_ReconCommand_AIR_CAL = 2,
  ReconCmdMsg_ReconCommand_START_RECON = 3,
  ReconCmdMsg_ReconCommand_STOP_RECON = 4,
  ReconCmdMsg_ReconCommand_UPDATE_MANUAL_BAD_DETS = 5,
  ReconCmdMsg_ReconCommand_UPDATE_PARAM = 6,
  ReconCmdMsg_ReconCommand_REINITIALIZE_RECON = 7,
  ReconCmdMsg_ReconCommand_EXIT_RECON = 8,
  ReconCmdMsg_ReconCommand_AIR_DATA_VALIDATION = 9,
  ReconCmdMsg_ReconCommand_ReconCmdMsg_ReconCommand_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReconCmdMsg_ReconCommand_ReconCmdMsg_ReconCommand_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReconCmdMsg_ReconCommand_IsValid(int value);
const ReconCmdMsg_ReconCommand ReconCmdMsg_ReconCommand_ReconCommand_MIN = ReconCmdMsg_ReconCommand_OFFSET_AND_AIR_CAL;
const ReconCmdMsg_ReconCommand ReconCmdMsg_ReconCommand_ReconCommand_MAX = ReconCmdMsg_ReconCommand_AIR_DATA_VALIDATION;
const int ReconCmdMsg_ReconCommand_ReconCommand_ARRAYSIZE = ReconCmdMsg_ReconCommand_ReconCommand_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReconCmdMsg_ReconCommand_descriptor();
inline const ::std::string& ReconCmdMsg_ReconCommand_Name(ReconCmdMsg_ReconCommand value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReconCmdMsg_ReconCommand_descriptor(), value);
}
inline bool ReconCmdMsg_ReconCommand_Parse(
    const ::std::string& name, ReconCmdMsg_ReconCommand* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReconCmdMsg_ReconCommand>(
    ReconCmdMsg_ReconCommand_descriptor(), name, value);
}
enum ReconCmdMsg_ParamType {
  ReconCmdMsg_ParamType_NONE = 0,
  ReconCmdMsg_ParamType_NYLON_SCALE = 1,
  ReconCmdMsg_ParamType_BELT_HEIGHT = 2,
  ReconCmdMsg_ParamType_CENTER_DET = 3,
  ReconCmdMsg_ParamType_NONLIN_TAB = 4,
  ReconCmdMsg_ParamType_ReconCmdMsg_ParamType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReconCmdMsg_ParamType_ReconCmdMsg_ParamType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReconCmdMsg_ParamType_IsValid(int value);
const ReconCmdMsg_ParamType ReconCmdMsg_ParamType_ParamType_MIN = ReconCmdMsg_ParamType_NONE;
const ReconCmdMsg_ParamType ReconCmdMsg_ParamType_ParamType_MAX = ReconCmdMsg_ParamType_NONLIN_TAB;
const int ReconCmdMsg_ParamType_ParamType_ARRAYSIZE = ReconCmdMsg_ParamType_ParamType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReconCmdMsg_ParamType_descriptor();
inline const ::std::string& ReconCmdMsg_ParamType_Name(ReconCmdMsg_ParamType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReconCmdMsg_ParamType_descriptor(), value);
}
inline bool ReconCmdMsg_ParamType_Parse(
    const ::std::string& name, ReconCmdMsg_ParamType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReconCmdMsg_ParamType>(
    ReconCmdMsg_ParamType_descriptor(), name, value);
}
enum ReconStatusMsg_StatusType {
  ReconStatusMsg_StatusType_OFFSET_CAL = 0,
  ReconStatusMsg_StatusType_AIR_CAL = 1,
  ReconStatusMsg_StatusType_MANUAL_BAD_DETS = 2,
  ReconStatusMsg_StatusType_ReconStatusMsg_StatusType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReconStatusMsg_StatusType_ReconStatusMsg_StatusType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReconStatusMsg_StatusType_IsValid(int value);
const ReconStatusMsg_StatusType ReconStatusMsg_StatusType_StatusType_MIN = ReconStatusMsg_StatusType_OFFSET_CAL;
const ReconStatusMsg_StatusType ReconStatusMsg_StatusType_StatusType_MAX = ReconStatusMsg_StatusType_MANUAL_BAD_DETS;
const int ReconStatusMsg_StatusType_StatusType_ARRAYSIZE = ReconStatusMsg_StatusType_StatusType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReconStatusMsg_StatusType_descriptor();
inline const ::std::string& ReconStatusMsg_StatusType_Name(ReconStatusMsg_StatusType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReconStatusMsg_StatusType_descriptor(), value);
}
inline bool ReconStatusMsg_StatusType_Parse(
    const ::std::string& name, ReconStatusMsg_StatusType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReconStatusMsg_StatusType>(
    ReconStatusMsg_StatusType_descriptor(), name, value);
}
enum ReconStatusMsg_Status {
  ReconStatusMsg_Status_SUCCESS = 0,
  ReconStatusMsg_Status_FAIL = 1,
  ReconStatusMsg_Status_NOT_READY = 2,
  ReconStatusMsg_Status_ZIPPER_IN_BEAM = 3,
  ReconStatusMsg_Status_AIR_DATA_VALID = 4,
  ReconStatusMsg_Status_AIR_DATA_INVALID = 5,
  ReconStatusMsg_Status_ReconStatusMsg_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReconStatusMsg_Status_ReconStatusMsg_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReconStatusMsg_Status_IsValid(int value);
const ReconStatusMsg_Status ReconStatusMsg_Status_Status_MIN = ReconStatusMsg_Status_SUCCESS;
const ReconStatusMsg_Status ReconStatusMsg_Status_Status_MAX = ReconStatusMsg_Status_AIR_DATA_INVALID;
const int ReconStatusMsg_Status_Status_ARRAYSIZE = ReconStatusMsg_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReconStatusMsg_Status_descriptor();
inline const ::std::string& ReconStatusMsg_Status_Name(ReconStatusMsg_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReconStatusMsg_Status_descriptor(), value);
}
inline bool ReconStatusMsg_Status_Parse(
    const ::std::string& name, ReconStatusMsg_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReconStatusMsg_Status>(
    ReconStatusMsg_Status_descriptor(), name, value);
}
enum ReconEnum_CalReturnCode {
  ReconEnum_CalReturnCode_SUCCESS = 0,
  ReconEnum_CalReturnCode_TOO_MANY_BAD_VIEWS = 1,
  ReconEnum_CalReturnCode_WRONG_INPUT_SIZE = 2,
  ReconEnum_CalReturnCode_EXTRACT_RAW_DATA_ERROR = 3,
  ReconEnum_CalReturnCode_TOO_MANY_INTERIOR_ADJACENT_BAD_DETS = 4,
  ReconEnum_CalReturnCode_TOO_MANY_EDGE_ADJACENT_BAD_DETS = 5,
  ReconEnum_CalReturnCode_TOO_MANY_BAD_DETS_MAIN = 6,
  ReconEnum_CalReturnCode_TOO_MANY_BAD_DET_PAIRS_DE = 7,
  ReconEnum_CalReturnCode_WHOLE_MODULE_BAD = 8,
  ReconEnum_CalReturnCode_AIR_CONSISTENCY_CHECK_FAIL = 9,
  ReconEnum_CalReturnCode_BAD_DET_CONSISTENCY_CHECK_FAIL = 10,
  ReconEnum_CalReturnCode_ZIPPER_CHECK_FAIL = 11,
  ReconEnum_CalReturnCode_NO_PREVIOUS_CAL_TABLE = 12,
  ReconEnum_CalReturnCode_AIR_CONSISTENCY_OR_ZIPPER_CHECK_FAIL = 13,
  ReconEnum_CalReturnCode_TRIGGER_POS_NOT_ZERO_START = 14,
  ReconEnum_CalReturnCode_ReconEnum_CalReturnCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReconEnum_CalReturnCode_ReconEnum_CalReturnCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReconEnum_CalReturnCode_IsValid(int value);
const ReconEnum_CalReturnCode ReconEnum_CalReturnCode_CalReturnCode_MIN = ReconEnum_CalReturnCode_SUCCESS;
const ReconEnum_CalReturnCode ReconEnum_CalReturnCode_CalReturnCode_MAX = ReconEnum_CalReturnCode_TRIGGER_POS_NOT_ZERO_START;
const int ReconEnum_CalReturnCode_CalReturnCode_ARRAYSIZE = ReconEnum_CalReturnCode_CalReturnCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReconEnum_CalReturnCode_descriptor();
inline const ::std::string& ReconEnum_CalReturnCode_Name(ReconEnum_CalReturnCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReconEnum_CalReturnCode_descriptor(), value);
}
inline bool ReconEnum_CalReturnCode_Parse(
    const ::std::string& name, ReconEnum_CalReturnCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReconEnum_CalReturnCode>(
    ReconEnum_CalReturnCode_descriptor(), name, value);
}
// ===================================================================

class ReconCmdMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:analogic.ancp00.ReconCmdMsg) */ {
 public:
  ReconCmdMsg();
  virtual ~ReconCmdMsg();

  ReconCmdMsg(const ReconCmdMsg& from);

  inline ReconCmdMsg& operator=(const ReconCmdMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReconCmdMsg& default_instance();

  void Swap(ReconCmdMsg* other);

  // implements Message ----------------------------------------------

  inline ReconCmdMsg* New() const { return New(NULL); }

  ReconCmdMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReconCmdMsg& from);
  void MergeFrom(const ReconCmdMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReconCmdMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ReconCmdMsg_ReconCommand ReconCommand;
  static const ReconCommand OFFSET_AND_AIR_CAL =
    ReconCmdMsg_ReconCommand_OFFSET_AND_AIR_CAL;
  static const ReconCommand OFFSET_CAL =
    ReconCmdMsg_ReconCommand_OFFSET_CAL;
  static const ReconCommand AIR_CAL =
    ReconCmdMsg_ReconCommand_AIR_CAL;
  static const ReconCommand START_RECON =
    ReconCmdMsg_ReconCommand_START_RECON;
  static const ReconCommand STOP_RECON =
    ReconCmdMsg_ReconCommand_STOP_RECON;
  static const ReconCommand UPDATE_MANUAL_BAD_DETS =
    ReconCmdMsg_ReconCommand_UPDATE_MANUAL_BAD_DETS;
  static const ReconCommand UPDATE_PARAM =
    ReconCmdMsg_ReconCommand_UPDATE_PARAM;
  static const ReconCommand REINITIALIZE_RECON =
    ReconCmdMsg_ReconCommand_REINITIALIZE_RECON;
  static const ReconCommand EXIT_RECON =
    ReconCmdMsg_ReconCommand_EXIT_RECON;
  static const ReconCommand AIR_DATA_VALIDATION =
    ReconCmdMsg_ReconCommand_AIR_DATA_VALIDATION;
  static inline bool ReconCommand_IsValid(int value) {
    return ReconCmdMsg_ReconCommand_IsValid(value);
  }
  static const ReconCommand ReconCommand_MIN =
    ReconCmdMsg_ReconCommand_ReconCommand_MIN;
  static const ReconCommand ReconCommand_MAX =
    ReconCmdMsg_ReconCommand_ReconCommand_MAX;
  static const int ReconCommand_ARRAYSIZE =
    ReconCmdMsg_ReconCommand_ReconCommand_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ReconCommand_descriptor() {
    return ReconCmdMsg_ReconCommand_descriptor();
  }
  static inline const ::std::string& ReconCommand_Name(ReconCommand value) {
    return ReconCmdMsg_ReconCommand_Name(value);
  }
  static inline bool ReconCommand_Parse(const ::std::string& name,
      ReconCommand* value) {
    return ReconCmdMsg_ReconCommand_Parse(name, value);
  }

  typedef ReconCmdMsg_ParamType ParamType;
  static const ParamType NONE =
    ReconCmdMsg_ParamType_NONE;
  static const ParamType NYLON_SCALE =
    ReconCmdMsg_ParamType_NYLON_SCALE;
  static const ParamType BELT_HEIGHT =
    ReconCmdMsg_ParamType_BELT_HEIGHT;
  static const ParamType CENTER_DET =
    ReconCmdMsg_ParamType_CENTER_DET;
  static const ParamType NONLIN_TAB =
    ReconCmdMsg_ParamType_NONLIN_TAB;
  static inline bool ParamType_IsValid(int value) {
    return ReconCmdMsg_ParamType_IsValid(value);
  }
  static const ParamType ParamType_MIN =
    ReconCmdMsg_ParamType_ParamType_MIN;
  static const ParamType ParamType_MAX =
    ReconCmdMsg_ParamType_ParamType_MAX;
  static const int ParamType_ARRAYSIZE =
    ReconCmdMsg_ParamType_ParamType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ParamType_descriptor() {
    return ReconCmdMsg_ParamType_descriptor();
  }
  static inline const ::std::string& ParamType_Name(ParamType value) {
    return ReconCmdMsg_ParamType_Name(value);
  }
  static inline bool ParamType_Parse(const ::std::string& name,
      ParamType* value) {
    return ReconCmdMsg_ParamType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .analogic.ancp00.ReconCmdMsg.ReconCommand cmd_id = 1;
  void clear_cmd_id();
  static const int kCmdIdFieldNumber = 1;
  ::analogic::ancp00::ReconCmdMsg_ReconCommand cmd_id() const;
  void set_cmd_id(::analogic::ancp00::ReconCmdMsg_ReconCommand value);

  // optional .analogic.ancp00.ReconCmdMsg.ParamType param_type = 2;
  void clear_param_type();
  static const int kParamTypeFieldNumber = 2;
  ::analogic::ancp00::ReconCmdMsg_ParamType param_type() const;
  void set_param_type(::analogic::ancp00::ReconCmdMsg_ParamType value);

  // optional float param_value = 3;
  void clear_param_value();
  static const int kParamValueFieldNumber = 3;
  float param_value() const;
  void set_param_value(float value);

  // optional bool bypass_cal_checks = 4;
  void clear_bypass_cal_checks();
  static const int kBypassCalChecksFieldNumber = 4;
  bool bypass_cal_checks() const;
  void set_bypass_cal_checks(bool value);

  // @@protoc_insertion_point(class_scope:analogic.ancp00.ReconCmdMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int cmd_id_;
  int param_type_;
  float param_value_;
  bool bypass_cal_checks_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fRecon_2eproto();
  friend void protobuf_AssignDesc_proto_2fRecon_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRecon_2eproto();

  void InitAsDefaultInstance();
  static ReconCmdMsg* default_instance_;
};
// -------------------------------------------------------------------

class ReconStatusMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:analogic.ancp00.ReconStatusMsg) */ {
 public:
  ReconStatusMsg();
  virtual ~ReconStatusMsg();

  ReconStatusMsg(const ReconStatusMsg& from);

  inline ReconStatusMsg& operator=(const ReconStatusMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReconStatusMsg& default_instance();

  void Swap(ReconStatusMsg* other);

  // implements Message ----------------------------------------------

  inline ReconStatusMsg* New() const { return New(NULL); }

  ReconStatusMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReconStatusMsg& from);
  void MergeFrom(const ReconStatusMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReconStatusMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ReconStatusMsg_StatusType StatusType;
  static const StatusType OFFSET_CAL =
    ReconStatusMsg_StatusType_OFFSET_CAL;
  static const StatusType AIR_CAL =
    ReconStatusMsg_StatusType_AIR_CAL;
  static const StatusType MANUAL_BAD_DETS =
    ReconStatusMsg_StatusType_MANUAL_BAD_DETS;
  static inline bool StatusType_IsValid(int value) {
    return ReconStatusMsg_StatusType_IsValid(value);
  }
  static const StatusType StatusType_MIN =
    ReconStatusMsg_StatusType_StatusType_MIN;
  static const StatusType StatusType_MAX =
    ReconStatusMsg_StatusType_StatusType_MAX;
  static const int StatusType_ARRAYSIZE =
    ReconStatusMsg_StatusType_StatusType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StatusType_descriptor() {
    return ReconStatusMsg_StatusType_descriptor();
  }
  static inline const ::std::string& StatusType_Name(StatusType value) {
    return ReconStatusMsg_StatusType_Name(value);
  }
  static inline bool StatusType_Parse(const ::std::string& name,
      StatusType* value) {
    return ReconStatusMsg_StatusType_Parse(name, value);
  }

  typedef ReconStatusMsg_Status Status;
  static const Status SUCCESS =
    ReconStatusMsg_Status_SUCCESS;
  static const Status FAIL =
    ReconStatusMsg_Status_FAIL;
  static const Status NOT_READY =
    ReconStatusMsg_Status_NOT_READY;
  static const Status ZIPPER_IN_BEAM =
    ReconStatusMsg_Status_ZIPPER_IN_BEAM;
  static const Status AIR_DATA_VALID =
    ReconStatusMsg_Status_AIR_DATA_VALID;
  static const Status AIR_DATA_INVALID =
    ReconStatusMsg_Status_AIR_DATA_INVALID;
  static inline bool Status_IsValid(int value) {
    return ReconStatusMsg_Status_IsValid(value);
  }
  static const Status Status_MIN =
    ReconStatusMsg_Status_Status_MIN;
  static const Status Status_MAX =
    ReconStatusMsg_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    ReconStatusMsg_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return ReconStatusMsg_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return ReconStatusMsg_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return ReconStatusMsg_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .analogic.ancp00.ReconStatusMsg.StatusType status_type = 1;
  void clear_status_type();
  static const int kStatusTypeFieldNumber = 1;
  ::analogic::ancp00::ReconStatusMsg_StatusType status_type() const;
  void set_status_type(::analogic::ancp00::ReconStatusMsg_StatusType value);

  // optional .analogic.ancp00.ReconStatusMsg.Status status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::analogic::ancp00::ReconStatusMsg_Status status() const;
  void set_status(::analogic::ancp00::ReconStatusMsg_Status value);

  // @@protoc_insertion_point(class_scope:analogic.ancp00.ReconStatusMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int status_type_;
  int status_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fRecon_2eproto();
  friend void protobuf_AssignDesc_proto_2fRecon_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRecon_2eproto();

  void InitAsDefaultInstance();
  static ReconStatusMsg* default_instance_;
};
// -------------------------------------------------------------------

class ReconEnum : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:analogic.ancp00.ReconEnum) */ {
 public:
  ReconEnum();
  virtual ~ReconEnum();

  ReconEnum(const ReconEnum& from);

  inline ReconEnum& operator=(const ReconEnum& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReconEnum& default_instance();

  void Swap(ReconEnum* other);

  // implements Message ----------------------------------------------

  inline ReconEnum* New() const { return New(NULL); }

  ReconEnum* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReconEnum& from);
  void MergeFrom(const ReconEnum& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReconEnum* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ReconEnum_CalReturnCode CalReturnCode;
  static const CalReturnCode SUCCESS =
    ReconEnum_CalReturnCode_SUCCESS;
  static const CalReturnCode TOO_MANY_BAD_VIEWS =
    ReconEnum_CalReturnCode_TOO_MANY_BAD_VIEWS;
  static const CalReturnCode WRONG_INPUT_SIZE =
    ReconEnum_CalReturnCode_WRONG_INPUT_SIZE;
  static const CalReturnCode EXTRACT_RAW_DATA_ERROR =
    ReconEnum_CalReturnCode_EXTRACT_RAW_DATA_ERROR;
  static const CalReturnCode TOO_MANY_INTERIOR_ADJACENT_BAD_DETS =
    ReconEnum_CalReturnCode_TOO_MANY_INTERIOR_ADJACENT_BAD_DETS;
  static const CalReturnCode TOO_MANY_EDGE_ADJACENT_BAD_DETS =
    ReconEnum_CalReturnCode_TOO_MANY_EDGE_ADJACENT_BAD_DETS;
  static const CalReturnCode TOO_MANY_BAD_DETS_MAIN =
    ReconEnum_CalReturnCode_TOO_MANY_BAD_DETS_MAIN;
  static const CalReturnCode TOO_MANY_BAD_DET_PAIRS_DE =
    ReconEnum_CalReturnCode_TOO_MANY_BAD_DET_PAIRS_DE;
  static const CalReturnCode WHOLE_MODULE_BAD =
    ReconEnum_CalReturnCode_WHOLE_MODULE_BAD;
  static const CalReturnCode AIR_CONSISTENCY_CHECK_FAIL =
    ReconEnum_CalReturnCode_AIR_CONSISTENCY_CHECK_FAIL;
  static const CalReturnCode BAD_DET_CONSISTENCY_CHECK_FAIL =
    ReconEnum_CalReturnCode_BAD_DET_CONSISTENCY_CHECK_FAIL;
  static const CalReturnCode ZIPPER_CHECK_FAIL =
    ReconEnum_CalReturnCode_ZIPPER_CHECK_FAIL;
  static const CalReturnCode NO_PREVIOUS_CAL_TABLE =
    ReconEnum_CalReturnCode_NO_PREVIOUS_CAL_TABLE;
  static const CalReturnCode AIR_CONSISTENCY_OR_ZIPPER_CHECK_FAIL =
    ReconEnum_CalReturnCode_AIR_CONSISTENCY_OR_ZIPPER_CHECK_FAIL;
  static const CalReturnCode TRIGGER_POS_NOT_ZERO_START =
    ReconEnum_CalReturnCode_TRIGGER_POS_NOT_ZERO_START;
  static inline bool CalReturnCode_IsValid(int value) {
    return ReconEnum_CalReturnCode_IsValid(value);
  }
  static const CalReturnCode CalReturnCode_MIN =
    ReconEnum_CalReturnCode_CalReturnCode_MIN;
  static const CalReturnCode CalReturnCode_MAX =
    ReconEnum_CalReturnCode_CalReturnCode_MAX;
  static const int CalReturnCode_ARRAYSIZE =
    ReconEnum_CalReturnCode_CalReturnCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CalReturnCode_descriptor() {
    return ReconEnum_CalReturnCode_descriptor();
  }
  static inline const ::std::string& CalReturnCode_Name(CalReturnCode value) {
    return ReconEnum_CalReturnCode_Name(value);
  }
  static inline bool CalReturnCode_Parse(const ::std::string& name,
      CalReturnCode* value) {
    return ReconEnum_CalReturnCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:analogic.ancp00.ReconEnum)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fRecon_2eproto();
  friend void protobuf_AssignDesc_proto_2fRecon_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRecon_2eproto();

  void InitAsDefaultInstance();
  static ReconEnum* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ReconCmdMsg

// optional .analogic.ancp00.ReconCmdMsg.ReconCommand cmd_id = 1;
inline void ReconCmdMsg::clear_cmd_id() {
  cmd_id_ = 0;
}
inline ::analogic::ancp00::ReconCmdMsg_ReconCommand ReconCmdMsg::cmd_id() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconCmdMsg.cmd_id)
  return static_cast< ::analogic::ancp00::ReconCmdMsg_ReconCommand >(cmd_id_);
}
inline void ReconCmdMsg::set_cmd_id(::analogic::ancp00::ReconCmdMsg_ReconCommand value) {
  
  cmd_id_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconCmdMsg.cmd_id)
}

// optional .analogic.ancp00.ReconCmdMsg.ParamType param_type = 2;
inline void ReconCmdMsg::clear_param_type() {
  param_type_ = 0;
}
inline ::analogic::ancp00::ReconCmdMsg_ParamType ReconCmdMsg::param_type() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconCmdMsg.param_type)
  return static_cast< ::analogic::ancp00::ReconCmdMsg_ParamType >(param_type_);
}
inline void ReconCmdMsg::set_param_type(::analogic::ancp00::ReconCmdMsg_ParamType value) {
  
  param_type_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconCmdMsg.param_type)
}

// optional float param_value = 3;
inline void ReconCmdMsg::clear_param_value() {
  param_value_ = 0;
}
inline float ReconCmdMsg::param_value() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconCmdMsg.param_value)
  return param_value_;
}
inline void ReconCmdMsg::set_param_value(float value) {
  
  param_value_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconCmdMsg.param_value)
}

// optional bool bypass_cal_checks = 4;
inline void ReconCmdMsg::clear_bypass_cal_checks() {
  bypass_cal_checks_ = false;
}
inline bool ReconCmdMsg::bypass_cal_checks() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconCmdMsg.bypass_cal_checks)
  return bypass_cal_checks_;
}
inline void ReconCmdMsg::set_bypass_cal_checks(bool value) {
  
  bypass_cal_checks_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconCmdMsg.bypass_cal_checks)
}

// -------------------------------------------------------------------

// ReconStatusMsg

// optional .analogic.ancp00.ReconStatusMsg.StatusType status_type = 1;
inline void ReconStatusMsg::clear_status_type() {
  status_type_ = 0;
}
inline ::analogic::ancp00::ReconStatusMsg_StatusType ReconStatusMsg::status_type() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconStatusMsg.status_type)
  return static_cast< ::analogic::ancp00::ReconStatusMsg_StatusType >(status_type_);
}
inline void ReconStatusMsg::set_status_type(::analogic::ancp00::ReconStatusMsg_StatusType value) {
  
  status_type_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconStatusMsg.status_type)
}

// optional .analogic.ancp00.ReconStatusMsg.Status status = 2;
inline void ReconStatusMsg::clear_status() {
  status_ = 0;
}
inline ::analogic::ancp00::ReconStatusMsg_Status ReconStatusMsg::status() const {
  // @@protoc_insertion_point(field_get:analogic.ancp00.ReconStatusMsg.status)
  return static_cast< ::analogic::ancp00::ReconStatusMsg_Status >(status_);
}
inline void ReconStatusMsg::set_status(::analogic::ancp00::ReconStatusMsg_Status value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:analogic.ancp00.ReconStatusMsg.status)
}

// -------------------------------------------------------------------

// ReconEnum

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ancp00
}  // namespace analogic

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::analogic::ancp00::ReconCmdMsg_ReconCommand> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::ancp00::ReconCmdMsg_ReconCommand>() {
  return ::analogic::ancp00::ReconCmdMsg_ReconCommand_descriptor();
}
template <> struct is_proto_enum< ::analogic::ancp00::ReconCmdMsg_ParamType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::ancp00::ReconCmdMsg_ParamType>() {
  return ::analogic::ancp00::ReconCmdMsg_ParamType_descriptor();
}
template <> struct is_proto_enum< ::analogic::ancp00::ReconStatusMsg_StatusType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::ancp00::ReconStatusMsg_StatusType>() {
  return ::analogic::ancp00::ReconStatusMsg_StatusType_descriptor();
}
template <> struct is_proto_enum< ::analogic::ancp00::ReconStatusMsg_Status> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::ancp00::ReconStatusMsg_Status>() {
  return ::analogic::ancp00::ReconStatusMsg_Status_descriptor();
}
template <> struct is_proto_enum< ::analogic::ancp00::ReconEnum_CalReturnCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::analogic::ancp00::ReconEnum_CalReturnCode>() {
  return ::analogic::ancp00::ReconEnum_CalReturnCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fRecon_2eproto__INCLUDED
